export interface SearchResult {
  title: string;
  description: string;
  href: string;
  category: string;
  icon: "page" | "ministry" | "education" | "community" | "store" | "person" | "contact" | "info";
  tag?: string; // optional badge e.g. "Leadership", "Region", "Program"
}

export const searchIndex: SearchResult[] = [

  // ─── NATIONAL LEADERSHIP ──────────────────────────────────────────────────
  {
    title: "Dr. David Gilbert Bwire",
    description: "National Administrative Bishop – 5th National Overseer since 1977, 30+ years of pastoral service",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "Bishop",
  },
  {
    title: "National Administrative Bishop",
    description: "Dr. David Gilbert Bwire – Holds Honorary Doctor in Divinity, MBA, BSc in Christian Ministries",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "Role",
  },
  {
    title: "Ordained Bishop",
    description: "Dr. David Gilbert Bwire is an Ordained Bishop with World Missions (WM-USA) and CEO of Damajo Consultancy",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "Bishop",
  },

  // ─── REGIONAL BISHOPS / COUNCIL ────────────────────────────────────────────
  {
    title: "Samuel Wainaina",
    description: "National Secretary – North Central Region Bishop",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "National Secretary",
  },
  {
    title: "Dickson Tito Mwalili",
    description: "National Treasurer – Nairobi Region Bishop",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "National Treasurer",
  },
  {
    title: "Benea Alukwe Amakhungu",
    description: "National Education Coordinator – Coast Region Bishop",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "Education",
  },
  {
    title: "Simon Ngure Ben",
    description: "National Prayer Coordinator – Western Region Bishop",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "Prayer",
  },
  {
    title: "Protus Pamba Orima",
    description: "Regional Bishop – North Western Region",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "Regional Bishop",
  },
  {
    title: "Paul Obadha Ohuare",
    description: "National Convention Coordinator – Nyanza Region Bishop",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "Convention",
  },
  {
    title: "Council of Bishops",
    description: "Regional leadership covering North Central, Nairobi, Coast, Western, North Western, and Nyanza",
    href: "/about",
    category: "Leadership",
    icon: "person",
    tag: "Council",
  },

  // ─── CHURCH HISTORY & IDENTITY ────────────────────────────────────────────
  {
    title: "Founded in 1977",
    description: "NTCOGK was established on May 13, 1977 in Karatina, Nyeri District by Founder Francis Gachara",
    href: "/about",
    category: "History",
    icon: "info",
    tag: "1977",
  },
  {
    title: "Francis Gachara – Founder",
    description: "Founder of the New Testament Church of God Kenya, established in Karatina in 1977",
    href: "/about",
    category: "History",
    icon: "person",
    tag: "Founder",
  },
  {
    title: "Global Headquarters",
    description: "NTCOGK is connected to the global Church of God movement headquartered in Cleveland, Tennessee",
    href: "/about",
    category: "History",
    icon: "info",
    tag: "Global",
  },
  {
    title: "Church of God Movement",
    description: "Global denomination founded in 1886 in the United States, now spread across all continents",
    href: "/about",
    category: "History",
    icon: "info",
    tag: "Denomination",
  },
  {
    title: "Vision – Financially Sound Church",
    description: "Build a financially sound and spiritually mature church – leading soul-winning Pentecostal church in Kenya",
    href: "/about",
    category: "Vision & Mission",
    icon: "info",
    tag: "Vision",
  },
  {
    title: "Mission Statement",
    description: "Mobilize and motivate leadership into working towards achieving financial self-reliance and discipleship",
    href: "/about",
    category: "Vision & Mission",
    icon: "info",
    tag: "Mission",
  },
  {
    title: "Church Statistics",
    description: "15,000+ members · 224 local churches · 6 regional offices · 28+ districts across Kenya",
    href: "/about",
    category: "Statistics",
    icon: "info",
    tag: "Stats",
  },

  // ─── MINISTRIES ───────────────────────────────────────────────────────────
  {
    title: "Youth Ministry",
    description: "Igniting the future – empowering young people aged 13–35 in faith, purpose, and community",
    href: "/ministries/youth",
    category: "Ministries",
    icon: "ministry",
    tag: "Youth",
  },
  {
    title: "500+ Active Youth",
    description: "Youth Ministry has over 500 active members across 28+ regions in Kenya",
    href: "/ministries/youth",
    category: "Ministries",
    icon: "ministry",
    tag: "Youth",
  },
  {
    title: "Children's Ministry",
    description: "Kingdom Kids – nurturing faith in children from birth to 12 with age-appropriate Bible teaching",
    href: "/ministries/children",
    category: "Ministries",
    icon: "ministry",
    tag: "Children",
  },
  {
    title: "Kingdom Kids",
    description: "Safe, vetted-volunteer-led Sunday classes for children every week at NTCOGK",
    href: "/ministries/children",
    category: "Ministries",
    icon: "ministry",
    tag: "Kingdom Kids",
  },

  // ─── EDUCATION / COLLEGE ──────────────────────────────────────────────────
  {
    title: "Discipleship College",
    description: "Theology, biblical studies, and vocational courses at Pioneer Estate, Eldoret campus",
    href: "/college",
    category: "Education",
    icon: "education",
    tag: "College",
  },
  {
    title: "Diploma in Theology & Ministerial Studies",
    description: "1–2 year program for aspiring pastors and interns – includes Pastoral Counselling, Church History, Systematic Theology",
    href: "/college",
    category: "Education",
    icon: "education",
    tag: "Diploma",
  },
  {
    title: "Certificate in Biblical Studies & Leadership",
    description: "6–12 month certificate for youth leaders, small-group leaders, and ministry volunteers",
    href: "/college",
    category: "Education",
    icon: "education",
    tag: "Certificate",
  },
  {
    title: "Short Intensive Discipleship Course",
    description: "4-week evening/Saturday discipleship for new believers – covers Prayer, Bible Study Methods, Christian Living",
    href: "/college",
    category: "Education",
    icon: "education",
    tag: "Short Course",
  },
  {
    title: "Vocational & ICT Courses (KNEC)",
    description: "3–6 month KNEC-recognized computer applications and business skills courses for youth and adults",
    href: "/college",
    category: "Education",
    icon: "education",
    tag: "Vocational",
  },
  {
    title: "Leadership Train-the-Trainer (TOT)",
    description: "2–4 week intensive program covering leadership principles, communication, mentorship, and training methods",
    href: "/college",
    category: "Education",
    icon: "education",
    tag: "Leadership",
  },
  {
    title: "College Intake Periods",
    description: "New intakes in January, April, and September – fees payable via M-Pesa, Bank, or Cash",
    href: "/college",
    category: "Education",
    icon: "info",
    tag: "Admissions",
  },
  {
    title: "College Scholarships",
    description: "Church-sponsored scholarships available for eligible students – enquire at the admissions office",
    href: "/college",
    category: "Education",
    icon: "info",
    tag: "Scholarship",
  },
  {
    title: "Eldoret Campus Location",
    description: "Discipleship College is located at Pioneer Estate, Eldoret, Kenya – open Monday to Friday 8am–5pm",
    href: "/college",
    category: "Education",
    icon: "contact",
    tag: "Campus",
  },

  // ─── CONTACT & OFFICES ────────────────────────────────────────────────────
  {
    title: "National Headquarters – Karen",
    description: "Karen, Langata, Nairobi · P.O. Box 75, 00502 Karen · Phone: +254 759 120 222",
    href: "/contact",
    category: "Contact",
    icon: "contact",
    tag: "HQ",
  },
  {
    title: "Phone Number – NTCOGK",
    description: "Call us at +254 759 120 222 or email info@ntcogk.org",
    href: "/contact",
    category: "Contact",
    icon: "contact",
    tag: "Phone",
  },
  {
    title: "Email – info@ntcogk.org",
    description: "Send us an email at info@ntcogk.org for general enquiries, prayer requests, or ministry questions",
    href: "/contact",
    category: "Contact",
    icon: "contact",
    tag: "Email",
  },
  {
    title: "Nairobi Regional Office",
    description: "Regional office for Nairobi – serving churches and members in the Greater Nairobi area",
    href: "/contact",
    category: "Contact",
    icon: "contact",
    tag: "Regional",
  },
  {
    title: "Coast Regional Office",
    description: "Regional office for the Coast region – headquartered in Mombasa, Kenya",
    href: "/contact",
    category: "Contact",
    icon: "contact",
    tag: "Regional",
  },
  {
    title: "Western Regional Office",
    description: "Regional office serving Western Kenya churches and districts",
    href: "/contact",
    category: "Contact",
    icon: "contact",
    tag: "Regional",
  },

  // ─── GIVING ───────────────────────────────────────────────────────────────
  {
    title: "Give / Donate Online",
    description: "Support NTCOGK through tithes, offerings, missions giving, and building fund contributions",
    href: "/give",
    category: "Giving",
    icon: "info",
    tag: "Give",
  },
  {
    title: "M-Pesa Giving",
    description: "Give via M-Pesa – payment details available on the Give page",
    href: "/give",
    category: "Giving",
    icon: "info",
    tag: "M-Pesa",
  },
  {
    title: "Tithe & Offerings",
    description: "Bring your tithe and offering to support the work of God across Kenya's 224 local churches",
    href: "/give",
    category: "Giving",
    icon: "info",
    tag: "Tithe",
  },

  // ─── COMMUNITY & PAGES ───────────────────────────────────────────────────
  {
    title: "Church Events",
    description: "Upcoming services, seminars, conventions, and community gatherings across Kenya",
    href: "/events",
    category: "Community",
    icon: "community",
    tag: "Events",
  },
  {
    title: "Annual Convention",
    description: "NTCOGK hosts annual national conventions – find dates and location on the events page",
    href: "/events",
    category: "Community",
    icon: "community",
    tag: "Convention",
  },
  {
    title: "Photo Gallery",
    description: "Browse 66 photos from Youth, Children, Clergy, and Church Life ministries",
    href: "/gallery",
    category: "Community",
    icon: "community",
    tag: "Gallery",
  },
  {
    title: "Latest News",
    description: "Stories, updates, and announcements from across the NTCOGK community",
    href: "/contact",
    category: "Community",
    icon: "community",
    tag: "News",
  },
  {
    title: "Church Store",
    description: "Bibles, books, church merchandise and spiritual resources – Ksh prices, M-Pesa accepted",
    href: "/store",
    category: "Store",
    icon: "store",
    tag: "Store",
  },
  {
    title: "Member Portal",
    description: "Access your church membership records, contribution history, and member resources",
    href: "/auth",
    category: "Portals",
    icon: "page",
    tag: "Members",
  },
  {
    title: "Clergy Portal",
    description: "Resource center for ordained leaders, pastors, and clergy members",
    href: "/auth",
    category: "Portals",
    icon: "page",
    tag: "Clergy",
  },
  {
    title: "About NTCOGK",
    description: "Learn about our history, mission, vision, leadership, and regional structure",
    href: "/about",
    category: "Pages",
    icon: "page",
  },
  {
    title: "Sign In / Create Account",
    description: "Sign in or create your NTCOGK member account to access exclusive resources",
    href: "/auth",
    category: "Pages",
    icon: "page",
  },
];
